variable sa_name {
  description = "Service Account Name"
  default     = "mongodb"
}
variable sc_name {
  description = "Storage Class Name"
  default     = "sc-mongodb-standalone"
}

variable docker_registry_file {
  description = "Docker Authentication Configuration File"
  default     = "/Users/patrickpresto/.docker/config.json"
}
variable docker_registry_secret_name {
  description = "Docker Authentication Configuration File"
  default     = "regcred"
}

variable kmip_ca {
  default = <<EOT
-----BEGIN CERTIFICATE-----
MIIBrDCCAVKgAwIBAgIUSpW5KTJ8O4xRvetSRdkLwaIj0w4wCgYIKoZIzj0EAwIw
HTEbMBkGA1UEAxMSdmF1bHQta21pcC1kZWZhdWx0MB4XDTIwMDcxNTIzMzkzNloX
DTMwMDcxMzIzNDAwNlowKjEoMCYGA1UEAxMfdmF1bHQta21pcC1kZWZhdWx0LWlu
dGVybWVkaWF0ZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNnIHu5On0RFwKT5
K7/8RxJXCXanpYFnYk3nlzVF7ZKk3TPAlIb0kb7KqW84+kA+tlnLkFutEYv7/1hv
tLWt5xyjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
DgQWBBRHkzoM7AdRGvtxFtSAe0BJ1JA8+TAfBgNVHSMEGDAWgBTrUA0R+24gpaTn
nBmiOSjNS1qnQTAKBggqhkjOPQQDAgNIADBFAiByUaCt4aRCPY16rZ73OIUR33S7
DH0AxTvBiCVw65UqXAIhALjK0qojQykxNPI2rIfkW5naX2WLOMeCDVtozkehZ+Aa
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBnjCCAUWgAwIBAgIUYhM2oiH5ByjWMqLYpYBQuEU1Gw4wCgYIKoZIzj0EAwIw
HTEbMBkGA1UEAxMSdmF1bHQta21pcC1kZWZhdWx0MB4XDTIwMDcxNTIzMzkzNloX
DTMwMDcxMzIzNDAwNlowHTEbMBkGA1UEAxMSdmF1bHQta21pcC1kZWZhdWx0MFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnxhIxxS35jV8ULjR7j/GHLjYFclFfhQf
QkpiyanvGH9JSRHRv50vsw57KkTp7NpffP/0znv97XjzOW25jPX61KNjMGEwDgYD
VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOtQDRH7biCl
pOecGaI5KM1LWqdBMB8GA1UdIwQYMBaAFOtQDRH7biClpOecGaI5KM1LWqdBMAoG
CCqGSM49BAMCA0cAMEQCIGnhJX6cebrToLmR2c62jHBONBky3bMYt+yBYY5xRJeW
AiAcDtSppdNCED14v7odtnGASpHSzlhSBKCg9Bpojj41/w==
-----END CERTIFICATE-----
EOT
}

variable kmip_pem {
  default = <<EOT
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIANdgpMNHRJYdIOGl+iJeXAnvXXpN9U2Bn4FektyZp9hoAoGCCqGSM49
AwEHoUQDQgAEzrzSG5ifQIFWlaacnOlYzt20Aa80ZB7Mf7jkFEIWYSB7gvWDcEVW
T2IcHcYnEcHI7HbRGDWBGrwcLm88E7rYzw==
-----END EC PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIIBtDCCAVmgAwIBAgIUTpYoLLvdE+p7fAAxOhdNXtHRYHMwCgYIKoZIzj0EAwIw
KjEoMCYGA1UEAxMfdmF1bHQta21pcC1kZWZhdWx0LWludGVybWVkaWF0ZTAeFw0y
MDA3MTUyMzQxMDVaFw0yMDA3MjkyMzQxMzVaMCAxDjAMBgNVBAsTBWtJQ3l4MQ4w
DAYDVQQDEwVQTnNTTDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABM680huYn0CB
VpWmnJzpWM7dtAGvNGQezH+45BRCFmEge4L1g3BFVk9iHB3GJxHByOx20Rg1gRq8
HC5vPBO62M+jZzBlMA4GA1UdDwEB/wQEAwIDqDATBgNVHSUEDDAKBggrBgEFBQcD
AjAdBgNVHQ4EFgQUUsi79m+GPsxc8EoRd792fzlcTnUwHwYDVR0jBBgwFoAUR5M6
DOwHURr7cRbUgHtASdSQPPkwCgYIKoZIzj0EAwIDSQAwRgIhAOGX1L/7zM81BgyD
z8b/Q2pjmM6u3KZcoOgQVn9ldKWXAiEAy+KVizdzfBwApfyjeUS+p4RXb6r6BSOi
8eEMHDIcUEQ=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBrDCCAVKgAwIBAgIUSpW5KTJ8O4xRvetSRdkLwaIj0w4wCgYIKoZIzj0EAwIw
HTEbMBkGA1UEAxMSdmF1bHQta21pcC1kZWZhdWx0MB4XDTIwMDcxNTIzMzkzNloX
DTMwMDcxMzIzNDAwNlowKjEoMCYGA1UEAxMfdmF1bHQta21pcC1kZWZhdWx0LWlu
dGVybWVkaWF0ZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNnIHu5On0RFwKT5
K7/8RxJXCXanpYFnYk3nlzVF7ZKk3TPAlIb0kb7KqW84+kA+tlnLkFutEYv7/1hv
tLWt5xyjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
DgQWBBRHkzoM7AdRGvtxFtSAe0BJ1JA8+TAfBgNVHSMEGDAWgBTrUA0R+24gpaTn
nBmiOSjNS1qnQTAKBggqhkjOPQQDAgNIADBFAiByUaCt4aRCPY16rZ73OIUR33S7
DH0AxTvBiCVw65UqXAIhALjK0qojQykxNPI2rIfkW5naX2WLOMeCDVtozkehZ+Aa
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBnjCCAUWgAwIBAgIUYhM2oiH5ByjWMqLYpYBQuEU1Gw4wCgYIKoZIzj0EAwIw
HTEbMBkGA1UEAxMSdmF1bHQta21pcC1kZWZhdWx0MB4XDTIwMDcxNTIzMzkzNloX
DTMwMDcxMzIzNDAwNlowHTEbMBkGA1UEAxMSdmF1bHQta21pcC1kZWZhdWx0MFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnxhIxxS35jV8ULjR7j/GHLjYFclFfhQf
QkpiyanvGH9JSRHRv50vsw57KkTp7NpffP/0znv97XjzOW25jPX61KNjMGEwDgYD
VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOtQDRH7biCl
pOecGaI5KM1LWqdBMB8GA1UdIwQYMBaAFOtQDRH7biClpOecGaI5KM1LWqdBMAoG
CCqGSM49BAMCA0cAMEQCIGnhJX6cebrToLmR2c62jHBONBky3bMYt+yBYY5xRJeW
AiAcDtSppdNCED14v7odtnGASpHSzlhSBKCg9Bpojj41/w==
-----END CERTIFICATE-----
EOT
}