approle_path = "approle"
role_name    = "terraform"
k8s_path     = "k8s"
ssh_path     = "ssh"
kv_path      = "kv"
kv_secret_path  = "kv/database/config"
kv_secret_data = "{\"username\": \"admin\", \"password\": \"password\", \"ttl\": \"20s\"}"
